# Generated by Django 2.0.3 on 2018-04-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_auto_20180401_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='maindir',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='maindir', to='tree.Folder'),
        ),
    ]
