# Generated by Django 2.0.3 on 2018-04-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_user_maindir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='maindir',
        ),
    ]
